export type ManifestAtlas = { readonly name: string; readonly pages: readonly { readonly image: string; readonly data: string }[] };

export type ManifestTexture = {
  readonly id: string;
  readonly image: string;
  readonly anchor: { readonly x: number; readonly y: number };
};

export type ManifestFont = { readonly family: string; readonly file: string };

export type ManifestInput = {
  readonly atlases: readonly ManifestAtlas[];
  readonly textures: readonly ManifestTexture[];
  readonly fonts: readonly ManifestFont[];
  /** Pixels per world unit after resizing, for every sprite and texture id. */
  readonly pixelsPerUnit: Readonly<Record<string, number>>;
  /** Extra ids that resolve to another texture id. */
  readonly aliases: Readonly<Record<string, string>>;
};

/**
 * Generates `src/generated/assets.ts`. Files are imported (not fetched) so Vite serves them in dev and inlines
 * them as data URIs into the single-file build. Paths are relative to `src/generated/`.
 */
export function renderManifestModule(input: ManifestInput): string {
  const imports: string[] = [];
  const bind = (file: string): string => {
    const name = `asset${imports.length}`;
    imports.push(`import ${name} from ${JSON.stringify(`./${file}`)};`);

    return name;
  };
  const quote = (text: string) => JSON.stringify(text);
  const sortedEntries = (record: Readonly<Record<string, string | number>>) =>
    Object.entries(record)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, value]) => `    ${quote(key)}: ${typeof value === 'number' ? value : quote(value)},`);

  const atlases = input.atlases.map(
    (atlas) =>
      `    { name: ${quote(atlas.name)}, pages: [${atlas.pages.map((page) => `{ image: ${bind(page.image)}, data: ${bind(page.data)} }`).join(', ')}] },`,
  );
  const textures = input.textures.map(
    (texture) => `    { id: ${quote(texture.id)}, image: ${bind(texture.image)}, anchor: { x: ${texture.anchor.x}, y: ${texture.anchor.y} } },`,
  );
  const fonts = input.fonts.map((font) => `    { family: ${quote(font.family)}, url: ${bind(font.file)} },`);

  return [
    '// Generated by tools/assets/build.ts from assets-src/. Do not edit: run `npm run assets:build`.',
    ...imports,
    '',
    'export const ASSET_MANIFEST = {',
    ...section('atlases', '[', atlases, ']'),
    ...section('textures', '[', textures, ']'),
    ...section('fonts', '[', fonts, ']'),
    ...section('pixelsPerUnit', '{', sortedEntries(input.pixelsPerUnit), '}'),
    ...section('aliases', '{', sortedEntries(input.aliases), '}'),
    '};',
    '',
  ].join('\n');
}

function section(name: string, open: string, lines: readonly string[], close: string): string[] {
  return [`  ${name}: ${open}`, ...lines, `  ${close},`];
}
